### PR TITLE
New recipe tutorial

### PR DESCRIPTION
**Pull request by BoogieMonster1O1**
it works :tm:

### CODE REVIEW

**Comment by natanfudge** [comment]
There are no changes to the tutorial pages. The markdown files are the only point of this repository.

**Comment by BoogieMonster1O1** [comment]
> There are no changes to the tutorial pages. The markdown files are the only point of this repository.

there’s a new file

**Comment by BoogieMonster1O1** [comment]
oops forgot to push it

**Comment by BoogieMonster1O1** [comment]
> There are no changes to the tutorial pages. The markdown files are the only point of this repository.

pushed

**Pull request merged**
